### ISSUE TITLE
SpeakLeash and pandas

### ISSUE THREAD

**Issue by SensXYZ** [speakleash/speakleash-examples#4]
Create an example of how to quickly put data from the SpeakLeash into a data frame

**Comment by mglabska** [comment]
Code: [here](https://github.com/mglabska/speakleash_pckg/blob/master/dataframe.py)
Sample dataframe: https://github.com/mglabska/speakleash_pckg/blob/master/text_analysis.ipynb

**Comment by Samox1** [comment]
Added developed example in #8  --> resolve #13
